# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.3"

[[constraint]]
  name = "github.com/phayes/freeport"
  version = "1.0.2"

[[constraint]]
  name = "github.com/shurcooL/vfsgen"
  branch = "master"

[[constraint]]
  name = "github.com/skratchdot/open-golang"
  branch = "master"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.5"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  branch = "master"

[[constraint]]
  name = "github.com/99designs/gqlgen"
  version = "0.9.2"

[[constraint]]
  name = "github.com/awesome-gocui/gocui"
  branch = "master"

[[override]]
  name = "golang.org/x/tools"
  revision = "7e5bf9270d7061560865b8847c378236480f47e3"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.6.1"

[[constraint]]
  name = "github.com/xanzy/go-gitlab"
  version = "0.22.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  name = "github.com/MichaelMure/go-term-text"
  version = "0.2.4"

[[constraint]]
  branch = "master"
  name = "github.com/araddon/dateparse"